### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by francoiscrouzet** [AlZorba/iDig-Webapp#47]
### Discussed in https://github.com/esag-swiss/iDig-Webapp/discussions/28

# New tasks, August 2023

- [x] "search with id" currently only work with English ids
- [ ] add a "debug mode", and set it in the url. This would activate the console.log for maps, and extra display in the item form.
- [x] message "Veuillez sélectionner au moins un secteur" can be wrong : it is displayed even in cases where a trench is selected, but for instance the type "tiles" is selected.
- [x] translation of the interface strings, maybe with https://vue-i18n.intlify.dev
- [ ] the control bar disappears in mobile mode (use a Quasar layout?)
- [x] remove session storage
- [ ] Divide TheControlFields into 2 components: TheControlFields and TheControlType
- [x] Make `checkedFields` persistent per project (currently, the checkedFields persistence is common to all projects)
- [ ] Create a front-end data structure for labels, types, groups, translations, etc
- [x] TheItem : 
    - [x] divide into sub-components 
    - [x] update an item after saving it
    - [x] general refactor

# First things

- [x] Define data structure https://github.com/esag-swiss/iDig-Webapp/discussions/31
    - [x] Implement data structure
- [x] Rename components https://github.com/esag-swiss/iDig-Webapp/issues/15
- [x] Remove commented code or work in progress
- [x] remove data/preferences.json
    - [x] remove fields and types from data/preferences. Be careful, these fields are then used elsewhere, probably dead code so no errors. I can't find where anymore
    - [x] remove automatedfields, optionalautomatedfields, and put them in a separate file
    - [x] remove Agora and Amarynthos?

# Jean Sé

- [x] Git conflict : https://github.com/esag-swiss/iDig-Webapp/discussions/18
- [ ] Quasar setup and date picker https://github.com/esag-swiss/iDig-Webapp/issues/16
- [x] export CSV https://github.com/esag-swiss/iDig-Webapp/discussions/24
- [x] Fetch trenches by name's groups 

# Francois

- [ ] Examine input architecture
- [x] Refactor store/api into 2 parts: preparing data, and fetching them. Solution: async in the store. Where should data be prepared / set?
- [x] Unit test for the data structure
- [x] rethrow error in handleError() ☐ - necessary? ☐ - isn't it better to do a return reject(error)? ☐ - .catch(() => {});

# Both 

- [x] loading spinner component (with a `isLoading` state, updated in the apiclient) https://github.com/esag-swiss/iDig-Webapp/issues/29
- [x] Quasar table https://github.com/esag-swiss/iDig-Webapp/discussions/3
- [x] header disabled / changed when connected - disconnect button that sets data to null https://github.com/esag-swiss/iDig-Webapp/discussions/19
- [x] ESLint errors https://github.com/esag-swiss/iDig-Webapp/issues/22
- [ ] Responsiveness AND/OR using a Quasar drawer https://github.com/esag-swiss/iDig-Webapp/issues/17
- [ ] Nice display of error message:
    - [x] nice toast instead of alert
    - [ ] manage if one field is undefined 
    - [ ] if all fields are undefined, display "error"
    - [ ] Function to rewrite error messages ("or project")
- [x] Editing of entries is not reactive: after saving, it does not display the changes in the table
- [x] `isHiddenArray` (in 2 components) can crash if there are more fields or trenches

# Requests by Thierry and future dev

- [ ] Merge these 2 lists with this Roadmap list?
https://github.com/esag-swiss/iDig-Webapp/discussions/1
https://github.com/esag-swiss/iDig-Webapp/discussions/2

# Later

- [ ] if using Quasar, completely remove Bootstrap
- [ ] add a standalone mode (disconected from server) 
- [ ] Readme https://github.com/esag-swiss/iDig-Webapp/issues/14
- [ ] find a solution for the deprecated "escape" function - semi-CRITICAL. 
    - [ ] at least do a check that "escape" exists, and if not, display an alert
